baseUrl: 'https://$PRIMARY_SITE_URL/'
enabled: true
handle: default
hasUrls: true
language: en-US
name: AH_Konfigurator
primary: true
siteGroup: e3e5709d-5796-4b03-88ef-13dc49fb6cff # $SERVER_NAME
sortOrder: 1
