field: cdd761f6-8dae-41bd-9f22-96195852a5d0 # Modific Examples
fieldLayouts:
  7386b5f8-8d1b-4382-8290-c854c7d5b97a:
    tabs:
      -
        elements:
          -
            fieldUid: b62726b4-2fad-462a-89cd-59fef7566b9e # Modific Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7faf54e-4937-4b42-9cdc-c871c5eb4376 # Modific Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b62726b4-2fad-462a-89cd-59fef7566b9e: # Modific Number
    columnSuffix: uyhghvdw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: modificNumber
    instructions: ''
    name: 'Modific Number'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  c7faf54e-4937-4b42-9cdc-c871c5eb4376: # Modific Name
    columnSuffix: djxzlvjo
    contentColumnType: text
    fieldGroup: null
    handle: modificName
    instructions: ''
    name: 'Modific Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: modificExample
name: 'Modific Example'
sortOrder: 1
