field: c29e6f48-f40c-4f51-8192-f2ff41e20d61 # Options List
fieldLayouts:
  b55f3140-dddb-4079-9419-bb03828ee951:
    tabs:
      -
        elements:
          -
            fieldUid: 5a7bbdd0-e05a-4686-8ad6-69733c153631 # Options Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d724f930-0b4a-4518-9061-9633bb3d3165 # Options Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a7010ef0-5dd8-470d-b381-87e2c65801f8 # Options Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5a7bbdd0-e05a-4686-8ad6-69733c153631: # Options Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: optionsTitle
    instructions: ''
    name: 'Options Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a7010ef0-5dd8-470d-b381-87e2c65801f8: # Options Price
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: optionsPrice
    instructions: 'Leave empty if this option is included in the apartment price'
    name: 'Options Price'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  d724f930-0b4a-4518-9061-9633bb3d3165: # Options Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: optionsSubtitle
    instructions: ''
    name: 'Options Subtitle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: optionsListBlock
name: 'Options List Block'
sortOrder: 1
