field: 90aa87e5-d7df-459e-af54-61a89ab0703d # Room Settings
fieldLayouts:
  a0990ff5-ac43-46e3-8791-608fe3002a78:
    tabs:
      -
        elements:
          -
            fieldUid: bf4e9c0a-6e43-4a36-89aa-d5377c19064d # Group Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4eae802-e3d7-46d6-8b12-c7b1d8d84b69 # Enable Individual Solution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 5e51d2f1-7683-4e2a-aa8f-f5229f211cbc # Individual Solution Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b0fb83be-0f11-4e66-95e6-799107674824 # Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5e51d2f1-7683-4e2a-aa8f-f5229f211cbc: # Individual Solution Price
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: individualSolutionPrice
    instructions: ''
    name: 'Individual Solution Price'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  b0fb83be-0f11-4e66-95e6-799107674824: # Options
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: optionsList
    instructions: ''
    name: Options
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 38eef38e-9a04-4822-b483-ad0b129df62e # Option Title
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 45ea1de9-fd16-46ba-a60b-46f203684565 # Option Subtitle
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 12a425ad-edf0-4ce6-a9a7-153611f63df0 # Option Price
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_optionslist}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  bf4e9c0a-6e43-4a36-89aa-d5377c19064d: # Group Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: groupTitle
    instructions: ''
    name: 'Group Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c4eae802-e3d7-46d6-8b12-c7b1d8d84b69: # Enable Individual Solution
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: enableIndividualSolution
    instructions: ''
    name: 'Enable Individual Solution'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: options
name: Options
sortOrder: 2
