field: c6d5578f-e6cf-4171-8037-4bcaf4e95dd0 # Room Styles
fieldLayouts:
  f463b2c6-e134-4704-9b14-ee741d3fee1f:
    tabs:
      -
        elements:
          -
            fieldUid: b954fb35-7727-4c87-bf3e-d76e6ee5ead2 # Room Style Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 50b3d857-24ad-440c-ac90-b1755c399ad6 # Style Default Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  50b3d857-24ad-440c-ac90-b1755c399ad6: # Style Default Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: styleDefaultImage
    instructions: ''
    name: 'Style Default Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b954fb35-7727-4c87-bf3e-d76e6ee5ead2: # Room Style Name
    columnSuffix: msttcqsm
    contentColumnType: text
    fieldGroup: null
    handle: roomStyleName
    instructions: ''
    name: 'Room Style Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: roomStylesBlock
name: 'Room styles block'
sortOrder: 1
