field: 2bcc8509-bf80-42a0-9a84-e45c74dfc228 # Links
fieldLayouts:
  adb97b5a-890e-4a7c-9c19-9f6ef25fb2db:
    tabs:
      -
        elements:
          -
            fieldUid: 25a3cb2d-ffaf-4dc6-9a7c-e31da3582380 # Social Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 69214030-ca3b-49f2-a7aa-0d3f8163fb39 # Social link logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  25a3cb2d-ffaf-4dc6-9a7c-e31da3582380: # Social Link
    columnSuffix: jnvvbhww
    contentColumnType: text
    fieldGroup: null
    handle: socialLink
    instructions: ''
    name: 'Social Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  69214030-ca3b-49f2-a7aa-0d3f8163fb39: # Social link logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: socialLinkLogo
    instructions: ''
    name: 'Social link logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: socialLinks
name: 'Social Links'
sortOrder: 2
