columnSuffix: fkowmyaf
contentColumnType: text
fieldGroup: f242347d-e6aa-4938-afd6-c792e6b82650 # Results
handle: userData
instructions: ''
name: 'User Link'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
