field: 645c2af4-53dd-4222-94fc-622039c9f2b1
fieldLayouts:
  b94ec4c2-6328-4f61-b631-cc596123fea0:
    tabs:
      -
        elements:
          -
            fieldUid: 9dcd13ea-f0fc-451c-8676-68e4995ea9dc # Mods Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9dcd13ea-f0fc-451c-8676-68e4995ea9dc: # Mods Name
    columnSuffix: zsjrlwan
    contentColumnType: text
    fieldGroup: null
    handle: modsName
    instructions: ''
    name: 'Mods Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
