field: f9625c6d-6743-4e6a-8814-8515c93e0a1d # Styles
fieldLayouts:
  6598510f-a39c-4393-8e69-503f4182c28c:
    tabs:
      -
        elements:
          -
            fieldUid: 7caa9c39-61ca-49c1-9490-aa62f9d14649 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c3112aba-9614-4cb7-b90b-575c9f0eb8a4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1ce9b4d-6b63-4bf3-876a-694dfd7b24b3 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57e1b676-7d2b-42ef-8c52-11a349a6ef61 # Recommended
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 494f98c9-f91d-4864-a1ed-6fe7d4705cf5 # Modified Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7caa9c39-61ca-49c1-9490-aa62f9d14649: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: styleTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57e1b676-7d2b-42ef-8c52-11a349a6ef61: # Recommended
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: recommended
    instructions: ''
    name: Recommended
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  494f98c9-f91d-4864-a1ed-6fe7d4705cf5: # Modified Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: modifiedStyle
    instructions: 'Insert images with chooses style and modification'
    name: 'Modified Style'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_modifiedstyle}}'
      maxBlocks: ''
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  c1ce9b4d-6b63-4bf3-876a-694dfd7b24b3: # Featured Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: featuredImage
    instructions: ''
    name: 'Featured Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c3112aba-9614-4cb7-b90b-575c9f0eb8a4: # Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: ''
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
