field: 0c1f4d59-c00f-4749-ba15-33c2b81252fd # Mod Item Example
fieldLayouts:
  2b81c588-fb92-4a1e-808d-810a0b65da5f:
    tabs:
      -
        elements:
          -
            fieldUid: eaa979eb-d80b-45d2-82dc-746215d2aa68 # Mod Numb
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70fea5dc-8e05-4e3e-a0e5-800ff9cb29e8 # Mod Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7bf2789e-ef77-4721-8540-661a36f3137a # Mod Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ccecd47c-7c8b-4af1-b337-19c42d70ba83 # Mod Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7bf2789e-ef77-4721-8540-661a36f3137a: # Mod Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: modName
    instructions: ''
    name: 'Mod Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  70fea5dc-8e05-4e3e-a0e5-800ff9cb29e8: # Mod Style
    columnSuffix: fzzgmubo
    contentColumnType: text
    fieldGroup: null
    handle: modStyle
    instructions: ''
    name: 'Mod Style'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ccecd47c-7c8b-4af1-b337-19c42d70ba83: # Mod Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: modImage
    instructions: ''
    name: 'Mod Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d489016d-368f-476c-a4df-2f7b904e7306' # uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  eaa979eb-d80b-45d2-82dc-746215d2aa68: # Mod Numb
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: modNumb
    instructions: ''
    name: 'Mod Numb'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
