field: 90a4c34f-345f-469c-a8d8-e7b59c31d58e # Individual Solution
fieldLayouts:
  d8353f2e-608f-4434-8adc-73056511d031:
    tabs:
      -
        elements:
          -
            fieldUid: 77dafdea-025e-42a9-8411-283f0555ccac # Enable Individual Solution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bbd8fa27-c0d5-4ae7-8743-c54f8d7a8b3f # Individual Solution Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  77dafdea-025e-42a9-8411-283f0555ccac: # Enable Individual Solution
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: enableIndividualSolution
    instructions: ''
    name: 'Enable Individual Solution'
    searchable: false
    settings:
      default: false
      offLabel: 'No'
      onLabel: 'Yes'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  bbd8fa27-c0d5-4ae7-8743-c54f8d7a8b3f: # Individual Solution Price
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: individualSolutionPrice
    instructions: ''
    name: 'Individual Solution Price'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
