field: 4a3bba70-a34d-4ed6-a440-737d6e407722 # Modification Pin
fieldLayouts:
  7a7411cf-ac3f-4bc3-9945-1328e1b311fd:
    tabs:
      -
        elements:
          -
            fieldUid: dd3e52b6-bc3c-44f3-8147-8feb8f63ccca # Position X
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4c72639-0014-4390-864c-90c72b90df5d # Position Y
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a4c72639-0014-4390-864c-90c72b90df5d: # Position Y
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: positionY
    instructions: ''
    name: 'Position Y'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  dd3e52b6-bc3c-44f3-8147-8feb8f63ccca: # Position X
    columnSuffix: null
    contentColumnType: integer(10)
    fieldGroup: null
    handle: positionX
    instructions: ''
    name: 'Position X'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
