field: 6a33257c-c238-4d4f-9a69-356b7380b06e # Pins
fieldLayouts:
  f3b48808-45df-4eb5-8424-be1f61eb1447:
    tabs:
      -
        elements:
          -
            fieldUid: 90fe60bc-4d3f-4af4-b8e4-21687c4da55b # Top Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 15ca951a-4085-4b28-85f0-7cf86d20885c # Left Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  15ca951a-4085-4b28-85f0-7cf86d20885c: # Left Position
    columnSuffix: null
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: leftPosition
    instructions: ''
    name: 'Left Position'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '100'
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  90fe60bc-4d3f-4af4-b8e4-21687c4da55b: # Top Position
    columnSuffix: null
    contentColumnType: smallint(3)
    fieldGroup: null
    handle: topPosition
    instructions: ''
    name: 'Top Position'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: '100'
      min: '0'
      prefix: null
      previewCurrency: ''
      previewFormat: decimal
      size: null
      suffix: '%'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
